### ISSUE TITLE
Line issue 

### ISSUE THREAD

**Issue by thatoneeevee** [uheartbeast/astar-tilemap#19]
i am having an issue with the line that shows where you are gonna move the pawn, when i check error this is what pops up, i am new to godot so idk if this is a common issue or not 
![image](https://user-images.githubusercontent.com/65206840/218283955-2495b672-7e33-4e11-94fc-749c2a001af8.png)

**Comment by mashumafi** [comment]
I'll take a guess that you just copied the gdscripts files into your project. The examples depend on you defining certain actions in the input map.

Can you confirm by checking the settings by clicking on "Project" in the menu and open "Project Settings...". There is a tab called "Input Map", near the bottom there should be 2 actions `mouse_left` and `mouse_right`. If those are missing then you can add them.

It will look like this:
![image](https://user-images.githubusercontent.com/1059099/219242276-bc9277cf-11ca-4b9c-9e85-50d736f47146.png)
