### ISSUE TITLE
Decision on types

### ISSUE THREAD

**Issue by mashumafi** [uheartbeast/astar-tilemap#5]
I noticed type information is not really used. I know you avoid them in your YouTube tutorial videos because of the additional cognitive load they add. I think it would benefit to add them here to help with adoption and understanding of the code.

I think 2 questions need to be answered before adding types:
1. Should types be added? (I think the answer should be yes)
2. Should `Array` always be preferred or would `PoolStringArray`, `PoolVector2Array`, etc. be preferred?

If types are *not* going to be added then some standard of documenting should be adapted early.

**Comment by uheartbeast** [comment]
1. Yes! I was actually planning on adding types but hadn't started yet.
2. It seems to me that the main benefit for using **PoolStringArray** and **PoolVector2Array** is for performance while the benefit of **Array** is extra functions like pop_front and pop_back? This is just my understanding. I don't have a strong opinion on the matter. It seems using the optimized versions where we can would make sense? May require converting to Array in some cases I guess. I'm open to opinions on this.

**Comment by mashumafi** [comment]
Added some types
